spring.application.name=localbridge
spring.servlet.multipart.file-size-threshold=0B
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB
app.version=@app.version@

# Session Management Configuration
app.session.inactivity-timeout-seconds=3600
